### ISSUE TITLE
Scrolling Issue on Project Green Blog

### ISSUE THREAD

**Issue by SyrCode** [SyrRock/web#1]
If you Scroll Out, all is anchored correctly.
If you scroll in, all things will go look like creepy.

May fix with 

```css
*html bildid {
 position: absolute;
}
```

or

```css
*html bildid (
  position: relative;
)
```
